language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - development
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy --settings .m2/travis-settings.xml'
env:
  global:
  - secure: Cap77mkOGD3QNODie6f38rAxfmEJcWeSbFod6SKUHcQ+1sPiWVDuBkJNIWHHVznJEL97STHYE1RFCn9lFtHF2qUcAM7o/DrYn9sADb7j3MmXjWUt45JZ37Z8y09f8X7VoJ8w1/aCTl/KQY77VU3axMu/v9GQyjYYxxblxJG22y0=
  - secure: FnX2Nm2xaJw6iXzEexUbeSyd/VLAtfgHDMtWOZYxLIKcDgFHLz86bElKf1NIHuJ0TZmLz5B/bhBEarNJM0jDJ66xmxXE+HwL09uhLUvFL/ScNdT0/D4Y+gvMJtHmrohJJLqNet6uxzWsfaxz7qtyNSmIEdUA/YugebiDGmGTP+0=
